    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv  
        state: present

    - name: Install psycopg2
      ansible.builtin.pip:
        name: psycopg2-binary
        state: present

    - name: Install Django
      pip:
        name: Django
        state: present

    
    - name: Install Node.js dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - software-properties-common

    - name: Import NodeSource GPG key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: nodesource

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present

    - name: Install npm package @angular/cli
      npm:
        name: '@angular/cli'
        global: yes

       


   